CLASS /dmo/bp_travel_u28 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF /dmo/i_travel_u28 .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /dmo/bp_travel_u28 IMPLEMENTATION.
ENDCLASS.
